// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZombieLynxPortalAPI.Data;

#nullable disable

namespace ZombieLynxPortalAPI.Migrations
{
    [DbContext(typeof(ZombieLynxPortalAPIDbContext))]
    [Migration("20250604225312_AddLastLoginToUser")]
    partial class AddLastLoginToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PreviouslyLinkedAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UnlinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "ExternalId")
                        .IsUnique();

                    b.ToTable("PreviouslyLinkedAccounts");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Active = true,
                            Email = "admin@zombielynx.com",
                            PasswordHash = "$2a$11$a/zOFLEsdUzQhG58wxh.seE2bNVAttboiyAeAZRsGN.oWlrHfvCHq",
                            Role = "Admin",
                            Verified = false
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.AdminTicket", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AdminId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("AdminTickets");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            TicketId = 1,
                            AssignedAt = new DateTime(2025, 6, 4, 22, 53, 12, 328, DateTimeKind.Utc).AddTicks(8498)
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.EmailVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordImgUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscordMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("DiscordUserName")
                        .HasColumnType("text");

                    b.Property<string>("ImgUrlsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("MessageGroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("SentToDiscord")
                        .HasColumnType("boolean");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageGroupId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the first message in the ticket conversation.",
                            CreatedAt = new DateTime(2025, 6, 4, 22, 53, 12, 329, DateTimeKind.Utc).AddTicks(954),
                            ImgUrlsJson = "[]",
                            MessageGroupId = 1,
                            SentToDiscord = false,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Following up on the issue. Any updates?",
                            CreatedAt = new DateTime(2025, 6, 4, 23, 3, 12, 329, DateTimeKind.Utc).AddTicks(1111),
                            ImgUrlsJson = "[]",
                            MessageGroupId = 1,
                            SentToDiscord = false,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Please let me know if you need more details.",
                            CreatedAt = new DateTime(2025, 6, 4, 23, 13, 12, 329, DateTimeKind.Utc).AddTicks(1125),
                            ImgUrlsJson = "[]",
                            MessageGroupId = 1,
                            SentToDiscord = false,
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 4, 22, 53, 12, 328, DateTimeKind.Utc).AddTicks(9095),
                            IsGlobal = true,
                            Message = "Welcome to Zombie Lynx Portal!",
                            Subject = "Welcome!"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 3, 22, 53, 12, 328, DateTimeKind.Utc).AddTicks(9354),
                            IsGlobal = false,
                            Message = "New server update available.",
                            Subject = "Server Update"
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResets");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.ProcessedTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransactionId");

                    b.ToTable("ProcessedTransactions");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.TebexBasket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("TebexBaskets");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscordChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Bug",
                            CreatedAt = new DateTime(2025, 6, 4, 22, 53, 12, 328, DateTimeKind.Utc).AddTicks(7197),
                            Description = "Initial test ticket for the system.",
                            Game = "Ark:SA",
                            Server = "NA-East",
                            Status = "Open",
                            Subject = "Test Ticket",
                            UpdatedAt = new DateTime(2025, 6, 4, 22, 53, 12, 328, DateTimeKind.Utc).AddTicks(7282),
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserNotification", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("NotificationId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.HasKey("UserProfileId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("UserNotifications");

                    b.HasData(
                        new
                        {
                            UserProfileId = 1,
                            NotificationId = 1,
                            Id = 1,
                            IsRead = false
                        },
                        new
                        {
                            UserProfileId = 1,
                            NotificationId = 2,
                            Id = 2,
                            IsRead = false
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowMarketingEmails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("HasAcceptedTerms")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowMarketingEmails = true,
                            CreatedAt = new DateTime(2025, 6, 4, 22, 53, 12, 328, DateTimeKind.Utc).AddTicks(3957),
                            FirstName = "Admin",
                            HasAcceptedTerms = false,
                            LastName = "User",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserTicket", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserProfileId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("UserTickets");

                    b.HasData(
                        new
                        {
                            UserProfileId = 1,
                            TicketId = 1,
                            AssignedAt = new DateTime(2025, 6, 4, 22, 53, 12, 328, DateTimeKind.Utc).AddTicks(7958)
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.VoteResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("VoteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VotedFor")
                        .HasColumnType("boolean");

                    b.Property<int>("ZLGMemberId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VoteId");

                    b.HasIndex("ZLGMemberId");

                    b.ToTable("VoteResults");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.ZLGMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("ASALinked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("ASELinked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("DiscordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DiscordImgUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DiscordName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EosId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EpicImgUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("EpicName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MinecraftAvatarUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("MinecraftLinked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MinecraftUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MinecraftUuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("PermissionGroups")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PromoReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RustLinked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("SteamId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SteamImgUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SteamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimedPermissionGroups")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ZLGMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ASALinked = false,
                            ASELinked = false,
                            DiscordId = "1167715864339030015",
                            DiscordImgUrl = "https://picsum.photos/seed/100/40/40",
                            DiscordName = "AdminDiscord",
                            EosId = "eos-admin-id",
                            EpicName = "AdminEpic",
                            MinecraftAvatarUrl = "https://crafatar.com/avatars/550e8400-e29b-41d4-a716-446655440000",
                            MinecraftLinked = false,
                            MinecraftUsername = "AdminMinecraft",
                            MinecraftUuid = "550e8400-e29b-41d4-a716-446655440000",
                            PermissionGroups = "Default,Admins",
                            Points = 0,
                            RustLinked = false,
                            SteamId = "76561198021051513",
                            SteamName = "AdminSteam",
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.AdminTicket", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieLynxPortalAPI.Models.Ticket", "Ticket")
                        .WithMany("AdminTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.EmailVerification", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Message", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("MessageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Ticket");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.PasswordReset", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.TebexBasket", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Ticket", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserNotification", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.Notification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserProfile", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ZombieLynxPortalAPI.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserTicket", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.Ticket", "Ticket")
                        .WithMany("UserTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Vote", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.VoteResult", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.Vote", "Vote")
                        .WithMany()
                        .HasForeignKey("VoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieLynxPortalAPI.Models.ZLGMember", "ZLGMember")
                        .WithMany()
                        .HasForeignKey("ZLGMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vote");

                    b.Navigation("ZLGMember");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.ZLGMember", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Ticket", b =>
                {
                    b.Navigation("AdminTickets");

                    b.Navigation("Messages");

                    b.Navigation("UserTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
