// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZombieLynxPortalAPI.Data;

#nullable disable

namespace ZombieLynxPortalAPI.Migrations
{
    [DbContext(typeof(ZombieLynxPortalAPIDbContext))]
    [Migration("20250119231700_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "admin@zombielynx.com",
                            PasswordHash = "$2a$11$JhdQJu6gjHSUtBnfylE4qetIw1RdRrK07bKxdmb8SXM5VFU5qwQjS",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.AdminTicket", b =>
                {
                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AdminId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("AdminTickets");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            TicketId = 1,
                            AssignedAt = new DateTime(2025, 1, 19, 23, 16, 59, 927, DateTimeKind.Utc).AddTicks(1542)
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<int>("MessageGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageGroupId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is the first message in the ticket conversation.",
                            CreatedAt = new DateTime(2025, 1, 19, 23, 16, 59, 927, DateTimeKind.Utc).AddTicks(2237),
                            MessageGroupId = 1,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Following up on the issue. Any updates?",
                            CreatedAt = new DateTime(2025, 1, 19, 23, 26, 59, 927, DateTimeKind.Utc).AddTicks(2397),
                            MessageGroupId = 1,
                            UserProfileId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Please let me know if you need more details.",
                            CreatedAt = new DateTime(2025, 1, 19, 23, 36, 59, 927, DateTimeKind.Utc).AddTicks(2464),
                            MessageGroupId = 1,
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Game")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Bug",
                            CreatedAt = new DateTime(2025, 1, 19, 23, 16, 59, 927, DateTimeKind.Utc).AddTicks(272),
                            Description = "Initial test ticket for the system.",
                            Game = "Ark:SA",
                            Server = "NA-East",
                            Status = "Open",
                            Subject = "Test Ticket",
                            UpdatedAt = new DateTime(2025, 1, 19, 23, 16, 59, 927, DateTimeKind.Utc).AddTicks(357),
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Admin",
                            LastName = "User",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserTicket", b =>
                {
                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserProfileId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("UserTickets");

                    b.HasData(
                        new
                        {
                            UserProfileId = 1,
                            TicketId = 1,
                            AssignedAt = new DateTime(2025, 1, 19, 23, 16, 59, 927, DateTimeKind.Utc).AddTicks(976)
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.ZLGMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiscordId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DiscordImgUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DiscordName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EosId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EpicImgUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("EpicName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SteamId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SteamImgUrl")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SteamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ZLGMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscordId = "123456789012345678",
                            DiscordImgUrl = "https://cdn.discordapp.com/avatars/123456789012345678/admin-discord.png",
                            DiscordName = "AdminDiscord",
                            EosId = "eos-admin-id",
                            EpicImgUrl = "https://static.epicgames.com/admin-epic-avatar.png",
                            EpicName = "AdminEpic",
                            SteamId = "76561198021051512",
                            SteamImgUrl = "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/adm/adminsteam.jpg",
                            SteamName = "AdminSteam",
                            UserProfileId = 1
                        });
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.AdminTicket", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieLynxPortalAPI.Models.Ticket", "Ticket")
                        .WithMany("AdminTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Message", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("MessageGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Ticket", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserProfile", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("ZombieLynxPortalAPI.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.UserTicket", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.Ticket", "Ticket")
                        .WithMany("UserTickets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.ZLGMember", b =>
                {
                    b.HasOne("ZombieLynxPortalAPI.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("ZombieLynxPortalAPI.Models.Ticket", b =>
                {
                    b.Navigation("AdminTickets");

                    b.Navigation("Messages");

                    b.Navigation("UserTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
